use_frameworks!

platform :ios, '9.0'

target 'BananaTesting_Example' do
  pod 'BananaTesting', :path => '../'

  target 'BananaTesting_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
